### PR TITLE
Add utility to check ROI of a given type

### PR DESCRIPTION
**Pull request by sbesson**
Implement hasROI() as an images list filter in figure_scripts. 
Can be used in other scripts (e.g. kymograph / Line ROI)

### CODE REVIEW

**Comment by will-moore** [comment]
Sebastien, perhaps you could change the behaviour a little bit...
- Use imageId parameter instead of image. Then you can use the method before you even load the image.
- Change the arguments to roitypes = None, so that hasROI(imgId) by default checks for ANY ROI type.

We have a ticket #8975 that requires this behaviour in the Blitz Gateway, on the ImageWrapper:  image.hasROI(). In fact this should probably be called  hasROIs() plural, since we are checking for any ROIs, not a particular ROI.

You might as well add this to Blitz Gateway now? components/tools/OmeroPy/src/omero/gateway/**init**.py. under ImageWrapper. Use self._conn.getQueryService()

**Comment by will-moore** [comment]
NB: If you do put this on to Blitz Gateway, you can ignore the imageId parameter point above.

**Comment by sbesson** [comment]
Implemented getROICount() method in BlitzGateway

NB: The ROI owner check is defined as a function instead of using omero.api.RoiOptions (see https://trac.openmicroscopy.org.uk/ome/ticket/8990)

**Comment by will-moore** [comment]
Sebastien: apologies - I should have mentioned this earlier...
We'd like to keep all of the commits to BlitzGateway separate from all other commits, so that they can be cherry-picked by Carlos working only on the BlitzGateway.
Do you think you could rework that commit(s) so as to only include the BlitzGateway changes? 
It's great that you mention BlitzGateway in the commit message. That also helps us keep track of changes to it, so please continue to do that.
 Many Thanks,

**Comment by sbesson** [comment]
Reworking the branch history to dissociate BlitzGateway changes.

**Pull request closed without merging**
