### PR TITLE
Postdecorators/omeroweb tweaks

### PR DESCRIPTION
**Pull request by cneves**

### CODE REVIEW

**Comment by will-moore** [comment]
Shouldn't allowPublic be a method?

allowPublic(request.path)

and maybe if the allowPublic method is specified, you don't need to match the regex too?

return self.allowPublic and self.allowPublic() or settings.PUBLIC_URL_FILTER.match(request.path) is not None

**Comment by cneves** [comment]
@will-moore: Why would allowPublic be a method?

There are two levels of configuration here, and they are completely separate:
- Have a view that allows or disallows public access depending on URL (with PUBLIC_URL_FILTER)
- Have a view that always disallows public access regardless of URL (with allowPublic=False)

I don't see how the two collide or how a method would be cleaner for the API.

**Comment by will-moore** [comment]
@cneves OK, I understand now. I thought "disallow public by method" meant that you were using a method in a functional approach to decide if a particular url was allowed.

Just one more question: since you are requiring that allowPublic AND the regex match for a url to be public, you'd can't just do @login_required(allowPublic=True) and be done with it - you need to also be sure that you've configured the regex correctly. Is this really necessary? If you say allowPublic is True, don't you want that to take priority??

ie:
if allowPublic is not None:
    return allowPublic
return settings.PUBLIC_URL_FILTER.match(request.path) is not None

but if this doesn't work for you then nevermind. Users can always overwrite is_valid_public_url()

**Comment by cneves** [comment]
@will-moore yes, allowPublic=True is completely ignored on my approach as I don't use it, but I will fix that along with a cleanup agreed with Chris

**Comment by cneves** [comment]
@chris-allan @will-moore The two commits added (ok, there's a third for the merge of sprint17, sorry about that) change the allowPublic as discussed, revert the doConnectionCleanup reading from kwargs and prevent the decorator from cleaning up any connection it didn't create.

**Comment by joshmoore** [comment]
What's the status of this? Can it be closed? Is it needed for 4.4.0?

**Comment by chris-allan** [comment]
This code is all already in `sprint18-bugfixes`, closing.

**Pull request closed without merging**
